---
- hosts: "all"
  become: true
  vars:
    created_username: thane
    
  roles:
        -  ../roles/basic
        - role: artis3n.tailscale
          vars:
            # Example pulling the API key from the env vars on the host running Ansible
            tailscale_authkey: "{{ vault.tailscale.key }}"
            tailscale_args: "--ssh"
  tasks:
    - name: Allow ssh via vpn only
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#ListenAddress'
        line: "ListenAddress {{ ansible_tailscale0.ipv4.address }}"
    - name: Disable password authentication for root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'    
    - name: Restart sshd
      ansible.builtin.systemd_service:
        state: restarted
        name: sshd   